public enum TileType
{
    forest = 1,
    lake = 2,
    mountain = 3,
    plain = 4,
    forestForest = 11,
    forestLake = 12,
    forestMountain = 13,
    forestPlain = 14,
    lakeLake = 22,
    lakeMountain = 23,
    lakePlain = 24,
    mountainMountain = 33,
    mountainPlain = 34,
    plainPlain = 44,

    //forest = 1,
    //forestForest = 11,
    //forestLake = 12,
    //forestMountain = 13,
    //forestPlain = 14,
    //lake = 2,
    //lakeLake = 22,
    //lakeMountain = 23,
    //lakePlain = 24,
    //mountain = 3,
    //mountainMountain = 33,
    //mountainPlain = 34,
    //plain = 4,
    //plainPlain = 44,
}